server:
  contextPath=/server

spring:
  h2:
    console:
      enabled: false
  datasource:
    url: "jdbc:h2:file:./data/kinancity.db;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: 
    driverClassName: org.h2.Driver


  jpa:
    show-sql: false # Show or not log for each sql query
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update  
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect